# SPDX-FileCopyrightText: 2023 Vasco Guita <vasco@guita.org>
#
# SPDX-License-Identifier: MIT

name = "Hugo Theme Freedom"
license = "MIT"
licenselink = "https://github.com/vascoguita/hugo-theme-freedom/blob/master/LICENSE"
description = "A minimalist Hugo theme built with Bootstrap."
homepage = "https://github.com/vascoguita/hugo-theme-freedom"
tags = ["bootstrap", "minimal", "personal", "blog"]
features = ["blog"]
min_version = "0.41.0"

[author]
name = "Vasco Guita"
homepage = "https://vasco.guita.org"
