---
# SPDX-FileCopyrightText: 2023 Vasco Guita <vasco@guita.org>
#
# SPDX-License-Identifier: MIT

name: Lint Markdown

on: [push, pull_request, workflow_dispatch]  # yamllint disable-line rule:truthy

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'
