---
# SPDX-FileCopyrightText: 2023 Vasco Guita <vasco@guita.org>
#
# SPDX-License-Identifier: MIT

name: Lint Makefile

on: [push, pull_request, workflow_dispatch]  # yamllint disable-line rule:truthy

jobs:
  lint-makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Makefile
        uses: Uno-Takashi/checkmake-action@v2
